import Foundation

enum ArrivalFlow {
    static let steps: [ArrivalStep] = [
        ArrivalStep(
            id: "scene-safe",
            title: "Scene Safety",
            prompt: "Scene safe?",
            actionPrompt: "Check danger before approaching.",
            category: .safety,
            yesLabel: "Safe",
            yesEvent: "Scene safe confirmed",
            noLabel: "Unsafe",
            noEvent: "Scene unsafe",
            unsureLabel: "",
            yesAction: .continueFlow,
            noAction: .callEmergency,
            unsureAction: nil,
            helpTitle: "Check Scene Safety",
            helpSubtitle: "Your safety comes first.",
            helpItems: [
                ArrivalHelpItem(icon: "eye.fill", title: "Look first", detail: "Check traffic, fire, electricity, water, violence, chemicals, or unstable objects."),
                ArrivalHelpItem(icon: "figure.walk", title: "Keep distance", detail: "If unsafe, stay back and warn others away."),
                ArrivalHelpItem(icon: "phone.fill", title: "Escalate early", detail: "Call 000 if emergency services are needed.")
            ],
            warningText: "Do not approach an unsafe scene."
        ),
        ArrivalStep(
            id: "responsive",
            title: "Response",
            prompt: "Does the patient respond?",
            actionPrompt: "Talk clearly and gently touch both shoulders.",
            category: .assessment,
            yesLabel: "Responds",
            yesEvent: "Patient responsive",
            noLabel: "No response",
            noEvent: "Patient unresponsive",
            unsureLabel: "",
            yesAction: .continueFlow,
            noAction: .sendForHelp,
            unsureAction: nil,
            helpTitle: "Check Response",
            helpSubtitle: "Fast checks before moving on.",
            helpItems: [
                ArrivalHelpItem(icon: "text.bubble.fill", title: "Speak first", detail: "Say their name or give a simple command: open your eyes, squeeze my hand."),
                ArrivalHelpItem(icon: "hand.raised.fill", title: "Touch shoulders", detail: "Gently squeeze or tap both shoulders. Do not shake hard."),
                ArrivalHelpItem(icon: "eye.fill", title: "Look for response", detail: "Eyes opening, voice, movement, or following a command counts as responsive.")
            ],
            warningText: "No response means send for help and continue the flow."
        ),
        ArrivalStep(
            id: "urgent-help",
            title: "Urgent Help",
            prompt: "Need urgent help?",
            actionPrompt: "If responsive, do a quick airway, breathing, bleeding, and pain check.",
            category: .assessment,
            yesLabel: "Yes - send help",
            yesEvent: "Urgent help needed",
            noLabel: "No - continue",
            noEvent: "No urgent help identified",
            unsureLabel: "Unsure",
            unsureEvent: "Urgent help status unsure",
            yesAction: .sendForHelp,
            noAction: .checkAirway,
            unsureAction: .sendForHelp,
            helpTitle: "Decide Escalation",
            helpSubtitle: "Escalate early if unsure.",
            helpItems: [
                ArrivalHelpItem(icon: "lungs.fill", title: "Check breathing", detail: "Look for difficulty breathing, noisy breathing, or abnormal breathing."),
                ArrivalHelpItem(icon: "drop.fill", title: "Check major bleeding", detail: "Look quickly for heavy bleeding or signs of shock."),
                ArrivalHelpItem(icon: "exclamationmark.triangle.fill", title: "Escalate if concerned", detail: "Call 000 for serious symptoms, deterioration, or if you are unsure.")
            ],
            warningText: "If unsure, send for help."
        ),
        ArrivalStep(
            id: "send-help",
            title: "Send For Help",
            prompt: "Send for help now.",
            actionPrompt: "Call 000 or ask someone nearby. Send someone for AED if available.",
            category: .escalation,
            yesLabel: "Called / someone else",
            yesEvent: "000 called or bystander asked to call",
            noLabel: "Continue assessment",
            noEvent: "Continued assessment after help check",
            unsureLabel: "",
            unsureEvent: "",
            yesAction: .continueFlow,
            noAction: .continueFlow,
            unsureAction: nil,
            helpTitle: "Call 000 Clearly",
            helpSubtitle: "Put the phone on speaker if safe.",
            helpItems: [
                ArrivalHelpItem(icon: "location.fill", title: "Say location", detail: "Give the exact address, nearby landmark, and access point."),
                ArrivalHelpItem(icon: "person.fill.questionmark", title: "Say condition", detail: "State if the patient is unresponsive or not breathing normally."),
                ArrivalHelpItem(icon: "speaker.wave.2.fill", title: "Stay on line", detail: "Follow the call taker instructions until help arrives.")
            ],
            warningText: "If unsure, call 000."
        ),
        ArrivalStep(
            id: "airway",
            title: "Airway",
            prompt: "Airway clear?",
            actionPrompt: "Open mouth and check for obvious blockage.",
            category: .assessment,
            yesLabel: "Clear",
            yesEvent: "Airway appears clear",
            noLabel: "Blocked",
            noEvent: "Airway not clear",
            unsureLabel: "Unsure",
            unsureEvent: "Airway status unsure",
            yesAction: .checkBreathing,
            noAction: .continueFlow,
            unsureAction: .continueFlow,
            helpTitle: "Check Airway",
            helpSubtitle: "Keep it simple and safe.",
            helpItems: [
                ArrivalHelpItem(icon: "mouth.fill", title: "Look in mouth", detail: "Check for obvious fluid, vomit, or foreign material."),
                ArrivalHelpItem(icon: "arrow.turn.up.right", title: "Clear if visible", detail: "If material is visible, roll onto side and clear it safely."),
                ArrivalHelpItem(icon: "hand.point.up.left.fill", title: "Open airway", detail: "Use head tilt and chin lift if appropriate.")
            ],
            warningText: "Do not do blind finger sweeps."
        ),
        ArrivalStep(
            id: "clear-airway",
            title: "Clear Airway",
            prompt: "Clear visible blockage.",
            actionPrompt: "Roll onto side if needed. Remove only what you can see.",
            category: .assessment,
            yesLabel: "Cleared",
            yesEvent: "Airway cleared",
            noLabel: "Still blocked",
            noEvent: "Airway still blocked",
            unsureLabel: "Unsure",
            unsureEvent: "Airway clearance unsure",
            yesAction: .checkBreathing,
            noAction: .checkBreathing,
            unsureAction: .checkBreathing,
            helpTitle: "Clear Airway",
            helpSubtitle: "Only clear what is visible.",
            helpItems: [
                ArrivalHelpItem(icon: "arrow.turn.up.right", title: "Side position", detail: "Roll onto side if fluid, vomit, or loose material may drain out."),
                ArrivalHelpItem(icon: "eye.fill", title: "Visible only", detail: "Remove loose material only if you can clearly see it."),
                ArrivalHelpItem(icon: "lungs.fill", title: "Recheck breathing", detail: "After clearing, open airway and check breathing again.")
            ],
            warningText: "Do not put fingers blindly into the mouth."
        ),
        ArrivalStep(
            id: "breathing",
            title: "Breathing",
            prompt: "Breathing normally?",
            actionPrompt: "Look, listen, and feel for up to 10 seconds.",
            category: .assessment,
            yesLabel: "Normal",
            yesEvent: "Breathing normally",
            noLabel: "Not normal",
            noEvent: "Not breathing normally",
            unsureLabel: "Unsure",
            unsureEvent: "Breathing status unsure",
            yesAction: .recoveryPosition,
            noAction: .startCPR,
            unsureAction: .startCPR,
            helpTitle: "Check Breathing",
            helpSubtitle: "Decide quickly.",
            helpItems: [
                ArrivalHelpItem(icon: "lungs.fill", title: "Look", detail: "Watch chest or abdomen movement."),
                ArrivalHelpItem(icon: "ear.fill", title: "Listen and feel", detail: "Listen for air movement and feel breathing near the mouth."),
                ArrivalHelpItem(icon: "exclamationmark.triangle.fill", title: "Gasping is not normal", detail: "If absent, abnormal, or unsure, start CPR and use AED when available.")
            ],
            warningText: "If not breathing normally, start CPR."
        ),
        ArrivalStep(
            id: "cpr",
            title: "CPR",
            prompt: "Start CPR.",
            actionPrompt: "30 compressions : 2 breaths if trained.",
            category: .treatment,
            yesLabel: "Open CPR Counter",
            yesEvent: "CPR counter opened",
            noLabel: "AED attached",
            noEvent: "AED attached",
            unsureLabel: "Breathing now",
            unsureEvent: "Patient breathing after CPR",
            yesAction: .openCPRCounter,
            noAction: .getAED,
            unsureAction: .recoveryPosition,
            helpTitle: "Do CPR",
            helpSubtitle: "Push hard and fast.",
            helpItems: [
                ArrivalHelpItem(icon: "hand.raised.fill", title: "Hands centre chest", detail: "Place hands in the centre of the chest."),
                ArrivalHelpItem(icon: "metronome.fill", title: "100-120 per minute", detail: "Push hard and fast. Minimise pauses."),
                ArrivalHelpItem(icon: "arrow.2.circlepath", title: "30:2 if trained", detail: "Give 30 compressions then 2 breaths. If unable, keep compressions going.")
            ],
            warningText: "Use an AED as soon as it is available."
        ),
        ArrivalStep(
            id: "aed",
            title: "AED",
            prompt: "Use AED.",
            actionPrompt: "Turn it on and follow prompts.",
            category: .treatment,
            yesLabel: "AED attached",
            yesEvent: "AED attached",
            noLabel: "Shock delivered",
            noEvent: "Shock delivered",
            unsureLabel: "No shock advised",
            unsureEvent: "AED advised no shock",
            yesAction: .getAED,
            noAction: .startCPR,
            unsureAction: .startCPR,
            helpTitle: "Use AED",
            helpSubtitle: "Follow the device voice prompts.",
            helpItems: [
                ArrivalHelpItem(icon: "power.circle.fill", title: "Turn on AED", detail: "Open the lid or press power, then follow prompts."),
                ArrivalHelpItem(icon: "rectangle.on.rectangle.angled.fill", title: "Place pads", detail: "Expose chest and place pads exactly as shown on the pads."),
                ArrivalHelpItem(icon: "hand.raised.slash.fill", title: "Stand clear", detail: "Do not touch the patient during rhythm analysis or shock.")
            ],
            warningText: "Resume CPR when the AED tells you to."
        ),
        ArrivalStep(
            id: "monitoring",
            title: "Monitoring",
            prompt: "Keep monitoring.",
            actionPrompt: "If anything changes, recheck DRSABCD.",
            category: .observation,
            yesLabel: "Handover",
            yesEvent: "Handover preparation started",
            noLabel: "Timeline",
            noEvent: "Timeline opened for update",
            unsureLabel: "Condition changed",
            unsureEvent: "Condition changed",
            yesAction: .prepareHandover,
            noAction: .openTimeline,
            unsureAction: .monitor,
            helpTitle: "Monitor And Handover",
            helpSubtitle: "Keep the picture clear.",
            helpItems: [
                ArrivalHelpItem(icon: "waveform.path.ecg", title: "Watch changes", detail: "Breathing, response, pain, bleeding, and colour changes matter."),
                ArrivalHelpItem(icon: "list.bullet.clipboard.fill", title: "Record actions", detail: "Add treatments, times, and changes to the timeline."),
                ArrivalHelpItem(icon: "doc.text.fill", title: "Prepare handover", detail: "Summarise what happened, what you found, and what you did.")
            ],
            warningText: "Call 000 again if the condition worsens."
        )
    ]
}
